#!/usr/bin/env node
import {mkdir,writeFile,access} from 'node:fs/promises';import {resolve} from 'node:path';
const id=process.argv[2];if(!/^[a-z][a-z0-9-]{2,48}$/.test(id||''))throw new Error('Usage: retro-museum-create my-game');
const dir=resolve(id);try{await access(dir);throw new Error('Destination already exists');}catch(error){if(error.code!=='ENOENT')throw error;}
await mkdir(dir+'/dist',{recursive:true});
const manifest={schemaVersion:1,id,version:'1.0.0',title:{en:'My first museum game'},description:{en:'Reach ten points first. Replace this example with your own game.'},author:'Your name',license:'MIT',languages:['en'],players:{min:2,max:8},durationMinutes:15,runtime:'quickjs-v1',entry:'dist/game.rmg.json',permissions:[]};
const engine=`globalThis.RetroMuseumGame={create(players,saved){const s=saved||{scores:Object.fromEntries(players.map(p=>[p.id,0])),winner:null};return {status(){return {winner:s.winner,ended:Boolean(s.winner),requiredPlayers:s.winner?[]:Object.keys(s.scores)}},action(id,action){if(action!=='point'||!(id in s.scores)||s.winner)throw Error('Invalid action');if(++s.scores[id]>=10)s.winner=id;},advance(){return false},snapshot(){return JSON.parse(JSON.stringify(s))},save(){return JSON.parse(JSON.stringify(s))},release(){},addPlayer(){}}}};`;
const view=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font:24px system-ui;background:#132326;color:white;padding:2rem}button{padding:2rem;font:inherit;border-radius:1rem}li{margin:1rem}</style><h1>First to ten</h1><ul id="scores"></ul><button id="point">+1 point</button><script>const scores=document.querySelector('#scores'),button=document.querySelector('#point');button.onclick=()=>parent.postMessage({retroMuseum:1,type:'action',action:'point'},'*');addEventListener('message',e=>{if(e.source!==parent||e.data?.type!=='state'||e.data.retroMuseum!==1)return;const s=e.data.state;button.hidden=e.data.role!=='controller';button.disabled=s.phase!=='playing';scores.replaceChildren(...s.party.players.map(p=>{const li=document.createElement('li');li.textContent=(p.name||'Player '+p.number)+': '+(s.party.community?.scores?.[p.id]||0);return li;}));});parent.postMessage({retroMuseum:1,type:'ready'},'*');</script></html>`;
const license=await (await import('node:fs/promises')).readFile(new URL('./LICENSE',import.meta.url),'utf8');
await writeFile(dir+'/retro-museum.json',JSON.stringify(manifest,null,2));await writeFile(dir+'/engine.js',engine);await writeFile(dir+'/view.html',view);await writeFile(dir+'/LICENSE',license);
await writeFile(dir+'/build.mjs',`import {readFile,writeFile} from 'node:fs/promises';await writeFile('dist/game.rmg.json',JSON.stringify({manifest:JSON.parse(await readFile('retro-museum.json','utf8')),engine:await readFile('engine.js','utf8'),view:await readFile('view.html','utf8'),licenseText:await readFile('LICENSE','utf8'),assets:{}}));`);
await writeFile(dir+'/dist/game.rmg.json',JSON.stringify({manifest,engine,view,licenseText:license,assets:{}}));
await writeFile(dir+'/README.md','# '+id+'\n\nEdit your manifest, engine.js and view.html, then run `node build.mjs`. Read https://github.com/manaty/retro-museum-sdk/blob/main/GAME-QUALITY.md and test completion, draws and replay. Commit dist/game.rmg.json and submit your public GitHub repository to the Retro Museum marketplace.\n');console.log('Created '+dir);
