const words={invite:['Invite a player','Inviter un joueur','Mag-imbita ng manlalaro'],message:['Join my game on Retro Museum!','Rejoins ma partie sur Retro Museum !','Sumali sa laro ko sa Retro Museum!'],copied:['Invitation link copied','Lien d’invitation copié','Nakopya ang link ng imbitasyon'],manual:['Copy this link and send it to your friend.','Copie ce lien et envoie-le à ton ami.','Kopyahin ang link at ipadala sa kaibigan mo.'],close:['Close','Fermer','Isara']};
export const inviteText=(language,key)=>words[key][{en:0,fr:1,tl:2}[language]??0];
export async function shareInvitation({url,title='Retro Museum',language='en',navigator:nav=globalThis.navigator,document:doc=globalThis.document}){
 const parsed=new URL(url);if(!['https:','http:'].includes(parsed.protocol)||parsed.username||parsed.password)throw Error('Invalid invitation URL');
 const data={title,text:inviteText(language,'message'),url:parsed.href};
 if(typeof nav?.share==='function'){try{if(!nav.canShare||nav.canShare(data)){await nav.share(data);return {status:'shared',url:data.url};}}catch(error){if(error.name==='AbortError')return {status:'cancelled',url:data.url};}}
 try{if(!nav?.clipboard?.writeText)throw Error('Clipboard unavailable');await nav.clipboard.writeText(data.url);return {status:'copied',url:data.url};}catch{}
 if(doc){const input=doc.createElement('textarea');input.value=data.url;input.setAttribute('readonly','');input.style.cssText='position:fixed;left:0;top:0;opacity:0';doc.body.appendChild(input);input.select();let copied=false;try{copied=Boolean(doc.execCommand?.('copy'));}catch{}input.remove();if(copied)return {status:'copied',url:data.url};}
 return {status:'manual',url:data.url};
}
export function createInviteButton({container,url,language=()=> 'en',title=()=> 'Retro Museum',beforeShare=()=>{},notice=()=>{},buttonClass=''}){
 const button=document.createElement('button');button.type='button';button.className=buttonClass;button.dataset.invitePlayer='';
 const icon='<svg aria-hidden="true" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="m8 10 8-5M8 14l8 5"/><circle cx="5" cy="12" r="3"/><circle cx="19" cy="4" r="3"/><circle cx="19" cy="20" r="3"/></svg>';
 let busy=false,lastLabel;const update=()=>{const text=inviteText(language(),'invite');if(text!==lastLabel){button.innerHTML=icon+'<span>'+text+'</span>';button.setAttribute('aria-label',text);lastLabel=text;}button.disabled=busy||!url();};
 button.onclick=async()=>{if(busy||!url())return;busy=true;button.disabled=true;beforeShare();try{const result=await shareInvitation({url:url(),title:title(),language:language()});if(result.status==='copied')notice(inviteText(language(),'copied'));if(result.status==='manual'){
 const overlay=document.createElement('div');overlay.className='invite-link-dialog';overlay.setAttribute('role','dialog');overlay.setAttribute('aria-modal','true');overlay.setAttribute('aria-label',inviteText(language(),'invite'));overlay.style.cssText='position:fixed;inset:0;z-index:2000;background:#000c;display:flex;align-items:center;justify-content:center;padding:20px';
 const card=document.createElement('div');card.style.cssText='background:#19332c;color:white;padding:24px;border:1px solid #769b83;border-radius:16px;width:100%;max-width:420px';const label=document.createElement('p');label.textContent=inviteText(language(),'manual');const input=document.createElement('input');input.value=result.url;input.readOnly=true;input.setAttribute('aria-label',inviteText(language(),'invite'));input.style.cssText='width:100%;padding:12px;font-size:16px';input.onclick=()=>input.select();const close=document.createElement('button');close.textContent=inviteText(language(),'close');close.style.marginTop='15px';close.onclick=()=>{overlay.remove();button.focus();};card.append(label,input,close);overlay.append(card);document.body.append(overlay);input.focus();input.select();
 }}finally{busy=false;update();}};container.append(button);update();return {button,update};
}
